/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OracleAbi } from "./OracleAbi";

export { OracleAbi__factory } from "./factories/OracleAbi__factory";
