/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

import type { Enum, Option } from "./common";

export type AddressInput = { value: string };

export type AddressOutput = { value: string };

export type ContractIdInput = { value: string };

export type ContractIdOutput = { value: string };

export type IdentityInput = Enum<{
  Address: AddressInput;
  ContractId: ContractIdInput;
}>;

export type IdentityOutput = Enum<{
  Address: AddressOutput;
  ContractId: ContractIdOutput;
}>;

interface OracleAbiInterface extends Interface {
  functions: {
    owner: FunctionFragment;
    price: FunctionFragment;
    set_price: FunctionFragment;
  };

  encodeFunctionData(functionFragment: "owner", values?: undefined): Uint8Array;
  encodeFunctionData(functionFragment: "price", values?: undefined): Uint8Array;
  encodeFunctionData(
    functionFragment: "set_price",
    values: [BigNumberish]
  ): Uint8Array;

  decodeFunctionData(functionFragment: "owner", data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: "price", data: BytesLike): DecodedValue;
  decodeFunctionData(
    functionFragment: "set_price",
    data: BytesLike
  ): DecodedValue;
}

export class OracleAbi extends Contract {
  interface: OracleAbiInterface;
  functions: {
    owner: InvokeFunction<[], IdentityOutput>;

    price: InvokeFunction<[], BN>;

    set_price: InvokeFunction<[price: BigNumberish], void>;
  };
}
